dist: xenial
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO=django~=2.2
  - DJANGO=django~=3.0
install:
  - pip install -r requirements-dev.txt
  - "pip install $DJANGO -e ."
script:
  - flake8 lepo
  - py.test -vvv --cov .
after_success:
  - bash <(curl -s https://codecov.io/bash)
